Update Microsoft build of Go to 1.17.1-1

diff --git a/src/microsoft/1.16/stretch/Dockerfile b/src/microsoft/1.16/stretch/Dockerfile
--- a/src/microsoft/1.16/stretch/Dockerfile
+++ b/src/microsoft/1.16/stretch/Dockerfile
@@ -6,29 +6,31 @@
 
 FROM buildpack-deps:stretch-scm
 
-# gcc for cgo
-RUN apt-get update && apt-get install -y --no-install-recommends \
+# install cgo-related dependencies
+RUN set -eux; \
+	apt-get update; \
+	apt-get install -y --no-install-recommends \
 		g++ \
 		gcc \
 		libc6-dev \
 		make \
 		pkg-config \
-	&& rm -rf /var/lib/apt/lists/*
+	; \
+	rm -rf /var/lib/apt/lists/*
 
 ENV PATH /usr/local/go/bin:$PATH
 
 ENV GOLANG_VERSION 1.16.8
 
 RUN set -eux; \
-	\
-	dpkgArch="$(dpkg --print-architecture)"; \
+	arch="$(dpkg --print-architecture)"; arch="${arch##*-}"; \
 	url=; \
-	case "${dpkgArch##*-}" in \
+	case "$arch" in \
 		'amd64') \
 			url='https://dotnetbuildoutput.blob.core.windows.net/golang/microsoft/release-branch.go1.16/20210929.6/go.20210929.6.linux-amd64.tar.gz'; \
 			sha256='de756069c46eafae24bf07eb30116c0ec60c6e6a097588d6c28766806db2f6e2'; \
 			;; \
-		*) echo >&2 "error: unsupported architecture '$dpkgArch' (likely packaging update needed)"; exit 1 ;; \
+		*) echo >&2 "error: unsupported architecture '$arch' (likely packaging update needed)"; exit 1 ;; \
 	esac; \
 	build=; \
 	if [ -z "$url" ]; then \
@@ -37,18 +39,18 @@ RUN set -eux; \
 		url=null; \
 		sha256=null; \
 		echo >&2; \
-		echo >&2 "warning: current architecture ($dpkgArch) does not have a corresponding Go binary release; will be building from source"; \
+		echo >&2 "warning: current architecture ($arch) does not have a compatible Go binary release; will be building from source"; \
 		echo >&2; \
 	fi; \
 	\
-# NO MICROSOFT_UPSTREAM: Change ".asc" to ".sig" to match the filename we publish.
+# NO MICROSOFT_UPSTREAM: Change ".asc" to ".sig" to match the filename we publish. https://github.com/microsoft/go/issues/181
 	wget -O go.tgz.asc "$url.sig" --progress=dot:giga; \
 # END NO MICROSOFT_UPSTREAM
 	wget -O go.tgz "$url" --progress=dot:giga; \
-	echo "$sha256 *go.tgz" | sha256sum --strict --check -; \
+	echo "$sha256 *go.tgz" | sha256sum -c -; \
 	\
 # https://github.com/golang/go/issues/14739#issuecomment-324767697
-	export GNUPGHOME="$(mktemp -d)"; \
+	GNUPGHOME="$(mktemp -d)"; export GNUPGHOME; \
 # NO MICROSOFT_UPSTREAM: Grab the public key used for the Microsoft builds of Go. https://github.com/microsoft/go/issues/47
 	wget -O microsoft-managed-lang-compiler.asc 'https://download.microsoft.com/download/f/a/2/fa2420dd-3f08-4621-82cf-5a22abcbc8f9/microsoft-managed-lang-compiler.asc'; \
 	gpg --batch --import microsoft-managed-lang-compiler.asc; \
